# Dockerfile-backend

FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y ffmpeg git && \
    pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy rest of the backend code
COPY . .

# Expose backend port
EXPOSE 8000

# Start backend server
CMD ["python", "start.py"]
